#!groovy

// Generated by IBM TransformationAdvisor
// Sun Feb 17 22:59:09 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}